apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-lidar
  labels:
    k8s-app: graph-lidar
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: graph-lidar
  template:
    metadata: 
      labels:
        k8s-app: graph-lidar
    spec:
      containers:
      - name: graph-lidar
        image: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
        command: ["sleep", "infinity"]
        volumeMounts:
          - mountPath: /root/main
            name: ivannia-volume
        resources:
          limits:
            memory: "8G"
            cpu: "1"
          requests:
             memory: "8G"
             cpu: "1"
      volumes:
        - name: ivannia-volume
          persistentVolumeClaim:
            claimName: ivannia-volume